rm( list = ls( ) ) 
graphics.off()
getwd()
setwd('C:\\Users\\User\\Desktop\\Gustavo\\Unicamp\\Mestrado\\1sem2021\\dm026\\aula_dplyr')
library(dplyr)
library(ggplot2)
library(data.table)
library(readr)
library(readxl)
dir.create('temp')
dir.create('temp_nov')